apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-pgadmin-svc"
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}