apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ .Release.Name }}-pgadmin-config
 namespace: {{ .Values.namespace }}
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "PostgreSQL DB",
           "Group": "Servers",
           "Port": 5432,
           "Username": "postgres",
           "Host": "postgressql.postgres.local",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
         }
       }
   }