---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaffold-app
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: scaffold
  template:
    metadata:
      labels:
        app: scaffold
    spec:
      containers:
        - name: scaffold
          image: hubproxy.docker.internal:5555/learn-scaffold:latest
          imagePullPolicy: Always
          env: []
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: scaffold-svc
spec:
  selector:
    app: scaffold
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
